# Generated by Django 6.0.6 on 2026-06-29 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='CLIENTE')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_mod', models.CharField(max_length=20, unique=True, verbose_name='REF. MOD')),
                ('description', models.CharField(max_length=250, verbose_name='DESCRIÇÃO')),
                ('tooling_material', models.CharField(max_length=100, verbose_name='MATERIAL FERRAMENTAL')),
                ('part_material', models.CharField(max_length=100, verbose_name='MATERIAL PEÇA')),
                ('gross_weight', models.CharField(max_length=50, verbose_name='PESO BRUTO PEÇA')),
                ('mold_cavities', models.IntegerField(verbose_name='FIGURAS MOLDES')),
                ('box_quantity', models.CharField(max_length=50, verbose_name='QTDE CX')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='items_photos/', verbose_name='FOTO')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.customer', verbose_name='CLIENTE')),
            ],
            options={
                'verbose_name': 'Item do Produto',
                'verbose_name_plural': 'Itens do Produto',
            },
        ),
        migrations.CreateModel(
            name='ProjectProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='DATA INICIAL')),
                ('status', models.CharField(choices=[('montar_pasta', 'MONTAR PASTA USINAGEM'), ('aguardando_bloco', 'AGUARDANDO BLOCO'), ('em_usinagem', 'EM USINAGEM'), ('concluido', 'CONCLUÍDO')], default='montar_pasta', max_length=50, verbose_name='SITUAÇÃO')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='OBSERVAÇÕES')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='DT. ÚLT. ALT.')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='projects.productitem', verbose_name='ITEM')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='RESP.')),
            ],
            options={
                'verbose_name': 'Processo do Projeto',
                'verbose_name_plural': 'Processos do Projeto',
            },
        ),
    ]
